# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestByndyusoft():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def wait_for_window(self, timeout = 2):
    time.sleep(round(timeout / 1000))
    wh_now = self.driver.window_handles
    wh_then = self.vars["window_handles"]
    if len(wh_now) > len(wh_then):
      return set(wh_now).difference(set(wh_then)).pop()
  
  def test_byndyusoft(self):
    # Test name: Byndyusoft
    # Step # | name | target | value | comment
    # 1 | open | https://www.google.ru/ |  | 
    self.driver.get("https://www.google.ru/")
    # 3 | click | name=q |  | 
    self.driver.find_element(By.NAME, "q").click()
    # 4 | type | name=q | Byndyusoft | 
    self.driver.find_element(By.NAME, "q").send_keys("Byndyusoft")
    # 5 | sendKeys | name=q | ${KEY_ENTER} | 
    self.driver.find_element(By.NAME, "q").send_keys(Keys.ENTER)
    # 6 | click | xpath=//h3 |  | 
    self.vars["window_handles"] = self.driver.window_handles
    # 7 | selectWindow | handle=${win9768} |  | 
    self.driver.find_element(By.XPATH, "//h3").click()
    # 8 | click | css=.btn--lg |  | 
    self.vars["win9768"] = self.wait_for_window(2000)
    # 9 | assertText | linkText=8 800 775-15-21 | 8 800 775-15-21 | 
    self.driver.switch_to.window(self.vars["win9768"])
    # 10 | assertText | linkText=sales@byndyusoft.com | sales@byndyusoft.com | 
    self.driver.find_element(By.CSS_SELECTOR, ".btn--lg").click()
    assert self.driver.find_element(By.LINK_TEXT, "8 800 775-15-21").text == "8 800 775-15-21"
    assert self.driver.find_element(By.LINK_TEXT, "sales@byndyusoft.com").text == "sales@byndyusoft.com"
  
